name: Bug report
description: Report a reproducible bug in one of the CLI packages
title: "[Bug] <package>: <short summary>"
labels: ["bug"]
body:
  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: text-chunker
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command / Reproduction
      description: Exact command(s) and input to reproduce
      placeholder: |
        text-chunker --strategy sentence sample.txt
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, package version
      placeholder: |
        macOS 14
        Python 3.11.9
        text-chunker 0.1.0
    validations:
      required: true
